name: example
description: Demonstrates how to use the fl_keyboard plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_waya: ^8.0.2
  fl_keyboard:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true